### ISSUE TITLE
Blank Screen when running vis

### ISSUE THREAD

**Issue by Velaseriat** [dpayne/cli-visualizer#26]
So... I am an idiot. Please have patience.
I am on Ubuntu 16.04, fresh install.

list of what I did:
export TERM=xterm-256color
sudo apt-get install libfftw3-dev libncursesw5-dev
sudo apt-get install libpulse-dev
make ENABLE_PULSE=1
./install.sh
pacmd list-sinks | grep -e 'name:' -e 'index' <-- to find audio source
vim ~/.config/vis/config
^ added 'audio.sources=pulse' and 'audio.pulse.source=0'
sudo apt-get install pulseaudio
but i cant help but notice that running pulseaudio gives me the following:
This message was edited
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
but i have sound

What should I do/have not done? 
If say, I have a music video playing in a different screen coming out of headphones, is there more I should be doing?

Thank you very much. Whatever your response is, I'll give this a star =)

**Comment by dpayne** [comment]
Could you run it directly with `./build/vis`?

**Comment by Velaseriat** [comment]
I tried it last night and it was a no go for me. I followed the steps above.

I see everyone getting it working, so it irks me that I'm having trouble.

Thanks for the response!

**Comment by dpayne** [comment]
Could you try with the line `audio.pulse.source=1` completely removed. On most systems, it should auto detect the source correctly.

**Comment by Velaseriat** [comment]
i took it out. still the same behavior. 

Man. Not sure what I did. I'm gonna test this on another machine (Lubuntu 16.04). Will report asap.

**Comment by kevinarefunny** [comment]
I'm having the same issue https://i.imgur.com/6Ze4Eml.png and this is my config file for vis https://paste.ubuntu.com/17596215/ and this is the config file for mpd https://paste.ubuntu.com/17596253/. I am also running Ubuntu 16.04.

**Comment by dpayne** [comment]
Could you post the output of `pacmd list-sinks` as well as the output of `ls -altr /tmp/mpd.fifo`?

**Comment by kevinarefunny** [comment]
Sure thing, here's the pacmd https://paste.ubuntu.com/17605212/ and here's the mpd.fifo https://paste.ubuntu.com/17605247/

**Comment by kevinarefunny** [comment]
It still does not work.

**Comment by dpayne** [comment]
When using mpd are you using, mpd to play music or some other player? Could you also post the output of `vis -h`?

**Comment by kevinarefunny** [comment]
Here's vis -h https://paste.ubuntu.com/17731385/ and when I normally listen to music, I use mpd+ncmpcpp

**Comment by DuckThom** [comment]
I'm on Arch Linux and I sometimes have a blank screen as well. Although I'm using pulse, not mpd, it might be worth a shot. 

I can fix it by opening `gnome-control-center` (I believe Ubuntu uses the same or at least a similar control panel) and then in the Sound preferences I manually select my output again. Then after running `vis`, I get the visualizer again.

**Comment by kevinarefunny** [comment]
I went into my settings and this is all I have. https://my.mixtape.moe/dmqqfu.webm

**Comment by zpsaras** [comment]
Using Xubuntu 16.04:
In response to the original poster, the issue is that you have run 
`./install.sh` 
after 
`make ENABLE_PULSE=1`

Running vis from the build/ directory after
`make ENABLE_PULSE=1`
gives me a working spectrum. None of the other visualizations seem to work, but this is certainly better than a blank screen!

**Comment by Andrew-Dickinson** [comment]
I'm also having this issue with Mint 18. I've tried running out of build/ and combinations of `make ENABLE_PULSE=1` and `./install.sh`. I have an identical setup to the OP, trying to use pulseaudio.

`pacmd list-sinks`
https://paste.ubuntu.com/23056481/
`ls -altr /tmp/mpd.fifo`
https://paste.ubuntu.com/23056483/

**Comment by jonwadsworth** [comment]
Same 'black screen' deal here.  Using mopidy instead of mpd; to trying to use pulse instead of mpd.  ncmpcpp for player.


`pacmd list-sinks  | grep -e 'name:'  -e 'index'`
results in:
`  * index: 0`
`	name: <alsa_output.pci-0000_00_1f.3.analog-stereo>`

so:

`visualizer.fps=20`
`audio.sources=pulse`
`audio.pulse.source=0`

run:
`~/Downloads/cli-visualizer-master $ build/vis -c ~/.config/vis/config 
`

Get BSOD (black screen of death)

Any ideas?  I'm game to try things; running Mint 17.

**Comment by arnauldb** [comment]
Hello,

thanks for cli-sualizer,

it doesn't work for me either...I have a black screen. I use mopidy and ncmpcpp.

my vis conf : 
http://www.cjoint.com/c/FIBveBLlWta

my .mpdconf : 
http://www.cjoint.com/c/FIBvhj7oGNa

thanks for any suggestion if you ave time,

**Comment by dpayne** [comment]
What ubuntu version are you using?

**Comment by arnauldb** [comment]
ubuntu mate, Ubuntu 15.10 wily.

**Comment by ArkaneCow** [comment]
I had this same problem, then I followed @zpsaras advice and edited the ./install.sh file to contain `make ENABLE_PULSE=1` instead of `make`. I am running Ubuntu 16.04 with default audio settings on Unity.

**Comment by snehesht** [comment]
try editing install.sh and change `make` to `make ENABLE_PULSE=1`

**Comment by dpayne** [comment]
I enabled pulseaudio support by default for linux. I don't think this explains all of the issues here. Since I could not reproduce the issue in on my box, it is pretty hard to narrow down.

**Comment by jonwadsworth** [comment]
Can you identify the particulars of your box Darby?
Kernel?  Distro?
Thanks!

**Comment by dpayne** [comment]
Sorry for the late response here, I don't have as much as I'd like for side projects ( : I've pushed a few fixes in the last day. @jonwadsworth could you try re-building now?

**Comment by gnuraspberry** [comment]
I had this problem tonight, using pulseaudio. Not sure what this is worth but everything started working once I installed libpulse-dev like the README told me too. I was so sure that I had it though.. oh well. I'm running debian stretch, 4.8.0-1-amd64.

I was getting this exact error, removed my /bin/vis, deleted clone and re-cloned, used the install.sh and it worked on first try.

Sorry if this is useless information, I thought I would share here just in case it helps anything since I was having this issue.

**Comment by jonwadsworth** [comment]
It's working now for me!  I'm not sure where I built the visualizer last time, so I totally re-cloned & re-built everything.  Works PERFECT for me.  Thanks!!

**Comment by rosshadden** [comment]
Still doesn't work for me.  Not sure which commit made it start showing just a blank screen, but I'll try to bisect to find it.

**Comment by rosshadden** [comment]
I went pretty far back in time (`1.2`) and it still doesn't work, whether I build with `ENABLE_PULSE=1` or not.  This leads me to believe something changed in an external dependency.  Also worth noting that the two non-default visualizers work when I cycle through them with `space`.  It is the main, default one that does not work.  This tells me it's not an issue with detecting pulseaudio or the correct sink.

**Comment by dpayne** [comment]
Based on your description what is probably broken something in ncurses, possibly wide characters or setting the background color. Could you set try setting the spectrum character in the config to a regular ascii character and then a UTF character, for example


    visualizer.spectrum.character=#

    visualizer.spectrum.character=❚

**Comment by rosshadden** [comment]
@dpayne It was indeed the character.  Both of those worked.  Do you know what could have changed for me in the past few months to make this stop working like it used to?

I use Arch Linux, and my terminal is `termite`.

**Comment by dpayne** [comment]
My guess is the ncurses library changed in someway. I'll debug some more tonight. It does work for on Arch for me, but my ncurses library is a custom build.

**Comment by dpayne** [comment]
@rosshadden could you try again with the latest version on master.

**Comment by rosshadden** [comment]
@dpayne Latest version works great, thanks!

**Comment by dpayne** [comment]
I'm going to close this ticket. I know that a few of the above issues are unrelated to the latest fix for ncurses, but this ticket has been a catch all for any blank screen issue for the visualizer and it is hard to distinguish exactly what issue someone is talking about. Anyone on the ticket who still has issues, fill free to open a new one for your specific error.

**Comment by luxpir** [comment]
Blank screen on Debian Stretch resolved by installing `libpulse-dev`, changing `make` to `make ENABLE_PULSE=1` and re-running `./install.sh`. No need to restart pulse or remove previous build. Thanks to @gnuraspberry and @ArkaneCow for tips.

Thanks for vis!

**Comment by sMx7d** [comment]
Thx mate!
@luxpir and every one also <3

work for me (ubuntu 20)
